"""The contract a platform backend must satisfy.

Everything OS-specific in qam lives behind this protocol: registering the
global hotkey, staying resident, the clipboard, notifications and launching
things. Porting to another desktop means adding one subpackage here - the
wheel, config and action layers stay untouched.
"""

from __future__ import annotations

from typing import Callable, Protocol


class Platform(Protocol):
    name: str

    # -- installation -----------------------------------------------------
    def install_hotkey(self, key: str) -> str: ...
    def uninstall_hotkey(self) -> str: ...
    def conflicting_binding(self, key: str) -> str | None: ...
    def install_service(self, executable: list[str], source_root: str | None = None) -> str: ...
    def uninstall_service(self) -> str: ...
    def install_desktop_entry(
        self, executable: list[str], source_root: str | None = None
    ) -> str: ...
    def uninstall_desktop_entry(self) -> str: ...

    # -- runtime ----------------------------------------------------------
    def set_clipboard(self, text: str) -> None: ...
    def read_clipboard(self, on_text: Callable[[str], None]) -> None: ...
    def notify(self, title: str, body: str = "") -> None: ...
    def launch_app(self, desktop_id: str) -> None: ...
    def open_path(self, path: str) -> None: ...
    def open_uri(self, uri: str) -> None: ...
    def run_command(self, command: str, shell: bool = False) -> None: ...

    # -- diagnostics ------------------------------------------------------
    def describe(self) -> list[tuple[str, str, bool]]:
        """Rows of (check, detail, ok) for `qam doctor`."""
